New db structure with simone
hulahoops123/mentorme pull request #1
Opened 2022-06-20 13:24 UTC by hulahoops123

Hi Simone. I hope this works

2022-06-20 20:26 UTC, Zelig880 requested changes
I tried to provide you some comments (i will provide more as we modify the code further).

I think the main change for you should be the introduction of a state management and the removal of the "watch/responsive" data as it is not actually needed now.

I can explain further as we go along, but the idea is that when an application is loaded. the changed that happen AFTER the load of the application can be replicated on the Frontend without the need to contact the server.. (so if you click SEND, there is no need fo you to re-read that value from the server as you know that you send SEND anyway, so you can add that message in the list of messages directly)

2022-06-20 20:26 UTC, Zelig880 commented on src/components/MsgDisplay.vue
>    <ul v-for="item of gotMessages">
gotMessages is the wrong name as it seem to refer to a boolean not an array

- [ ] Rename `gotMessages` to `messages`

2022-06-20 20:26 UTC, Zelig880 commented on src/components/MsgDisplay.vue
> +    <h5 style="color: red" v-if="item.sender === myUserName">
A message should not be an heading but a paragraph `p`

- [ ] Change this to be a `p` element

2022-06-20 20:26 UTC, Zelig880 commented on src/components/MsgDisplay.vue
> +    <h4 style="color: blue" v-if="item.sender === palName">
A message should not be an heading but a paragraph p

- [ ] Change this to be a p element

2022-06-20 20:26 UTC, Zelig880 commented on src/components/MsgDisplay.vue
>        if (index == length - 1) {
always use === not ==

- [ ] Change to "==="

2022-06-20 20:26 UTC, Zelig880 commented on src/components/MsgDisplay.vue
> +          (palStatus.value === "transit" && singlemsg.sender === myUserName)
You may want to change this to actually be a method and give it a well descriptive name. At the moment this can just be understood by reading the comment above but it would be great to use descriptive methods so that it could read something like `if( isLastMessage()  && isComingBack() )`

Also I may be wrong, but you do not need the "home" and "away" because that is the only 3 values right? so unless it is in transit and you are not the sender it is ok, we can show the message, we do not have to check tof the value...

- [ ] Make methods so that it is more readable
- [ ] Remove the Home and away line

2022-06-20 20:26 UTC, Zelig880 commented on src/components/MsgDisplay.vue
>  const gstate: any = inject("global");
Using inject is a very bad antipatter in vue. You should either just pass the value down from the parent (that should be ok fo you as it is a small app) or use Pinia or create a Vue 3 composable that act as your store

- [ ] Replace inject as it is not very used in a vue environment

2022-06-20 20:26 UTC, Zelig880 commented on src/views/PidginHole.vue
> +console.log(foundFromFound.value);
I honestly do not think you should write your application to be so reactive to change as the pigeon takes 3 days to arrive.

It would be so much easier for you just to work thinking that the data will be loaded when the page is loaded and that is it! You are making your like super hard and it is really not needed.

- [ ] Remove all this reactive code. There is no need of it. Just load the value on first load for now, then we can add complexity later

2022-06-21 20:13 UTC, hulahoops123 commented on src/components/MsgDisplay.vue
>  const gstate: any = inject("global");
This is a diffficult one for me. I have never used pinia and I thought this was a composable. And the inject is in so many places. Can we work on the database first then come back to this. Maybe we will not need it at all.

2022-06-21 20:13 UTC, hulahoops123 commented on src/views/PidginHole.vue
> +console.log(foundFromFound.value);
I am trying. Please see what Ive done so far. I am having trouble.

2022-06-21 20:13 UTC, hulahoops123 commented on src/components/MsgDisplay.vue
> +          (palStatus.value === "transit" && singlemsg.sender === myUserName)
I am not sure if what I did here was correct?

2022-06-21 21:42 UTC, Zelig880 commented on src/components/MsgDisplay.vue
>  const gstate: any = inject("global");
No problem at all, I have just raised a new issue so that we do not forget about it! :)

2022-06-21 21:44 UTC, Zelig880 commented on src/components/MsgDisplay.vue
> +      }
Apologies I think I said methods in the comment, but this can also be declared as simple variable declarations:
`const isLastMessage = (index === length - 1)`
`const isComingBack = (palStatus.value === "transit" && singlemsg.sender != myUserName)`

2022-06-21 21:47 UTC, Zelig880 commented on src/views/PidginHole.vue
> +console.log(foundFromFound.value);
Can you provide more info on what is the trouble.. You did well in the code to remove the watch. We can work on the missing functionality in different patches now

2022-06-22 04:37 UTC, hulahoops123 commented on src/components/MsgDisplay.vue
>  const gstate: any = inject("global");
Thank you. I am eager to understand this better.

2022-06-22 04:37 UTC, hulahoops123 commented on src/views/PidginHole.vue
> +console.log(foundFromFound.value);
Yes the console log of foundMessages in pidginhole.vue just says promise pending but its working if I console log in firestore.ts. I dont really have the data?

2022-06-22 04:37 UTC, hulahoops123 commented on src/components/MsgDisplay.vue
> +      }
Ok yes looks better this way. Im sorry I dont know enough as yet to infer what you mean. I have to take it literally.
Another example - I googled antipatter. :)

2022-06-22 04:55 UTC, hulahoops123 commented
Keep it small and merge often. I read a book about it ;-)

2022-06-24 06:55 UTC, Zelig880 commented on src/views/PidginHole.vue
> +console.log(foundFromFound.value);
You have to "return" the data from the computed property:
`const foundFromFound = computed(() =>
  return foundPidgins.value.map((doc) => {
    return {
      doc,
    };
  })
);`

2022-06-24 06:56 UTC, Zelig880 commented on src/components/MsgDisplay.vue
> +      }
Do not apologise at every comment! :) PR are done on purpose for knowledge transfer, everything you learn from a comment, is a step closer to your goal!

2022-06-30 13:09 UTC, merged